apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-de-martin-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/martinsendati/repo-de-infraestructura.git
    path: dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: web-de-martin
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
